name: Sync LeetCode Submissions

on:
  workflow_dispatch: # Allows you to run this manually anytime
  schedule:
    - cron: '0 0 * * *' # Runs automatically every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: LeetCode Sync
        uses: joshcai/leetcode-sync@v1.7

        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          
          # Customization options:
          destination-folder: 'practice/leetcode'
          verbose: true
          commit-header: 'Sync LeetCode submission'

